name: run tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      - name: Create venv and install dependencies
        run: |
          make venv
      - name: lint
        run: |
          make lint
      - name: Run tests
        run: |
          make test
